"use client";
import "./globals.css";
import { useState, useEffect } from "react";

// export const metadata = {
//   title: "SmoakBook",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  return (
    <html lang="pt-br">
      <head>
        <title>Gerenciamento Petshop - PetFlow</title>
        <link rel="icon" href="/app/favicon.ico" />
      </head>
      <body className="bg-white">
        <div className="layout">
          {children}
        </div>
      </body>
    </html>
  );
}
